// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wevdjmdlsrljanttykzu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldmRqbWRsc3JsamFudHR5a3p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYzNDI3NTEsImV4cCI6MjA4MTkxODc1MX0.kucbr1-8eeMmrJPx4TFn2TMtNfl2e0EA7MkiXskOvlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,

    // Use PKCE so email-link scanners can't "consume" magic links.
    // This makes magic links most reliable when opened on the same device/browser.
    detectSessionInUrl: true,
    flowType: 'pkce',
  }
});